### ISSUE TITLE
Building issue in Defold 1.2.192

### ISSUE THREAD

**Issue by u546342** [Insality/druid#187]
Hi.
I got this error when trying to build the project with Defold 1.2.192 (84a9c89dfd5a2c3818c01e7c6777169272d9390b):

```ERROR: druid/styles/default/templates/druid_button_blue.gui:69: 'com.dynamo.bob.CompileExceptionError: Message type "dmGuiDDF.NodeDesc" has no field named "custom_type".'

Exception in thread "main" com.dynamo.bob.CompileExceptionError: Message type "dmGuiDDF.NodeDesc" has no field named "custom_type".
	at com.dynamo.bob.pipeline.ProtoUtil.merge(ProtoUtil.java:34)
	at com.dynamo.bob.pipeline.GuiBuilder.create(GuiBuilder.java:68)
	at com.dynamo.bob.Project.createTask(Project.java:397)
	at com.dynamo.bob.Project.createTask(Project.java:358)
	at com.dynamo.bob.Project.createTasks(Project.java:463)
	at com.dynamo.bob.Project.doBuild(Project.java:1127)
	at com.dynamo.bob.Project.build(Project.java:584)
	at com.dynamo.bob.Bob.mainInternal(Bob.java:699)
	at com.dynamo.bob.Bob.main(Bob.java:748)
Caused by: com.google.protobuf.TextFormat$ParseException: 69:3: Message type "dmGuiDDF.NodeDesc" has no field named "custom_type".
	at com.google.protobuf.TextFormat$Tokenizer.parseExceptionPreviousToken(TextFormat.java:753)
	at com.google.protobuf.TextFormat.mergeField(TextFormat.java:918)
	at com.google.protobuf.TextFormat.mergeField(TextFormat.java:949)
	at com.google.protobuf.TextFormat.merge(TextFormat.java:855)
	at com.google.protobuf.TextFormat.merge(TextFormat.java:801)
	at com.dynamo.bob.pipeline.ProtoUtil.merge(ProtoUtil.java:28)
	... 8 more
make: *** [buildweb] Error 1```

**Comment by Insality** [comment]
Hey! Thanks for the issue
The Druid project was builded with later Defold version

When Defold introduce new field in *.gui for example, it can't be opened in previous versions. I can't fix this ;)

As dependency should work as expected

**Comment by 546342** [comment]
>As dependency should work as expected

Unfortunately, it's not :( 
I use druid as a dependency in my project and I can't build it with bob.jar now because of this error. 
For myself, I solved this problem by deleting these files in the repository fork, but this is not the best solution.

**Comment by Insality** [comment]
Thanks for info! I'll take a look soon
I'll fix this if it affect on dependency
